spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cers
    username: "cers"
    password: "cers"
    driver-class-name: com.mysql.jdbc.Driver

  flyway:
    password: "cers"
    user: "cers"
    url: jdbc:mysql://localhost:3306/cers
